name: API Tests

on:
  push:
    branches:
      - main  # Change this if using a different branch
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API Tests
        run: newman run API_Testing_Collection.json -r cli,json --reporter-json-export results.json

      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-results
          path: results.json
