name: API Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman and Reporters
        run: |
          npm install -g newman newman-reporter-json newman-reporter-html

      - name: Run API Tests with Newman
        run: |
          newman run API_Testing_Collection.json -r cli,json,html --reporter-json-export results.json --reporter-html-export report.html

      - name: Upload Test Reports (JSON & HTML)
        uses: actions/upload-artifact@v3
        with:
          name: api-test-reports
          path: |
            results.json
            report.html
