name: API Testing Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Run Postman Collection
        run: |
          newman run postman/API_Testing_Collection.json -r cli,html --reporter-html-export result.html

      - name: Upload HTML report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: html-report
          path: ./result.html
