name: API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API Tests
        run: newman run API_Testing_Collection.json -r cli,junit --reporter-junit-export results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: results.xml
