name: API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Run Postman API Tests
        run: newman run API_Testing_Collection.json -r cli,json --reporter-json-export report.json

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: report.json
